"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['qwantz/dinoapp.py']
# DATA_FILES = ['qwantz/']
DATA_FILES=['qwantz/fetch.py', 'qwantz/fetchthread.py', 'qwantz/pilutil.py']
OPTIONS = dict(
    iconfile='qwantz.icns',
    argv_emulation=False,
    # packages='wx',
    site_packages=False,
    semi_standalone=True,
    # resources=['resources/License.txt'],
    plist=dict(
        CFBundleName               = "DinosaurComics",
        CFBundleShortVersionString = "0.2.0",     # must be in X.X.X format
        CFBundleGetInfoString      = "DinosaurComics 0.2.0",
        CFBundleExecutable         = "launch",
        CFBundleIdentifier         = "net.minrk.dinocomics",
    )
)
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

import os
import sys,shutil,glob
pjoin = os.path.join
pyver = sys.version.split()[0][:3]
Contents=pjoin("./dist",OPTIONS['plist']['CFBundleName']+'.app','Contents')
bootfile = pjoin(Contents,"Resources","__boot__.py")
if False and os.path.isfile(bootfile): # don't do this anymore
    print "patching bootfile"
    f = open(bootfile)
    tail = f.read()
    f.close()
    lines = ["import sys, os,site",
            "sys.path.insert(0,os.path.join(os.environ['RESOURCEPATH'], 'lib', 'python%s'%(sys.version[:3]), 'lib-dynload'))",
            "site.addsitedir(os.path.join(os.environ['RESOURCEPATH'], 'lib', 'python%s'%(sys.version[:3])))",
            "site.addsitedir(os.path.join(os.environ['RESOURCEPATH'], 'lib', 'python%s'%(sys.version[:3]), 'site-packages'))",
            "site.addsitedir(os.path.join(os.environ['RESOURCEPATH'], 'lib', 'python%s'%(sys.version[:3]), 'site-packages.zip'))",
            "site.addsitedir('/System/Library/Frameworks/Python.framework/Versions/%s/Extras/lib/python'%(sys.version[:3]))",
            "print sys.path",
            tail]
    f = open(bootfile,'w')
    f.write('\n'.join(lines))
    f.close()

# cleanup incorrect includes:

site=pjoin(Contents, "Resources/lib/python%s"%pyver)
for subdir in "numpy scipy".split():
    pass
    if os.path.exists(pjoin(site, subdir)):
        shutil.rmtree(pjoin(site, subdir))

print "stripping unneeded libs"
for lib in glob.glob(pjoin(Contents, "Frameworks","libg*")):
    # pass
    os.remove(lib)

print "replacing executable and _imaging.so"
shutil.copyfile("_imaging.lite.so", pjoin(Contents, "Resources/lib/python%s/lib-dynload/_imaging.so"%pyver))
shutil.copyfile("load", pjoin(Contents, "MacOS/"))
# putting DYLD_LIBARY_PATH in plist
# import plistlib
# plist = plistlib.Parse(pjoin(Contents, 'Info.plist'))
# plist['LSEnvironment'] = dict(DYLD_LIBRARY_PATH=@executable)

print "forcing 32-bit python:"
target = pjoin(Contents, "MacOS", OPTIONS['plist']['CFBundleExecutable'])
temp=target+".tmp"
os.system("ditto --rsrc --arch i386 %s %s"%(target, temp))
shutil.move(temp, target)
print "making 32-bit only clone:"
os.system("ditto --rsrc --arch i386 %s %s"%(pjoin("dist", OPTIONS['plist']['CFBundleName']+".app"),pjoin("dist", OPTIONS['plist']['CFBundleName']+"32.app") ))



